name: 'Deploy to AWS S3'
description: 'Deplouy a static website via AWS S3'
inputs:
  bucket:
    description: 'The S3 bucket name'
  bucket-region:
    description: 'The region of the bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the built file'
    required: true

runs:
  using: node16
  main: 'main.js' # name of file to be executed for this custom action
